#!/bin/bash

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [[ -e .noverify ]]; then
	exit 0
fi

if echo $BRANCH | grep -Eq '^(main|master|develop)$'; then
	echo "HOOK: Pushing to disallowed branch (main, master, etc.)!"
	echo "HOOK: Use git push --no-verify to force this operation."
	exit 1
fi
